import { Injectable, BadGatewayException, Logger } from "@nestjs/common";
import axios from "axios";
import { parse } from "csv-parse/sync";
import type { NormalizedProduct, ProviderAdapter } from "../types";
import {
  hasNbPortalLogin,
  hasNbPriceListToken,
  NewBytesApiClient,
  parseNbCredentials,
  unwrapNbList,
  NB_API_BASE,
} from "../new-bytes-client";
import {
  applyDescription,
  descriptionMap,
  extractItemPatch,
  mapCsvProduct,
  mapJsonProduct,
  type NbCsvRow,
  type NbDescriptionItem,
  type NbJsonProduct,
} from "../new-bytes.mapper";

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

@Injectable()
export class NewBytesAdapter implements ProviderAdapter {
  readonly provider = "NEW_BYTES" as const;
  private readonly logger = new Logger(NewBytesAdapter.name);

  async syncAll(
    credentials: Record<string, string>,
    onPage: (items: NormalizedProduct[]) => Promise<void>
  ): Promise<void> {
    const creds = parseNbCredentials(credentials);
    if (hasNbPortalLogin(creds)) {
      try {
        await this.syncFromApi(creds.user!, creds.password!, onPage);
        return;
      } catch (err) {
        if (!hasNbPriceListToken(creds)) throw err;
        this.logger.warn(
          `Catálogo JSON de NewBytes falló (${err instanceof Error ? err.message : String(err)}). Uso lista de precios CSV.`
        );
        await this.syncFromCsv(creds.token!, onPage);
        return;
      }
    }
    if (hasNbPriceListToken(creds)) {
      await this.syncFromCsv(creds.token!, onPage);
      return;
    }
    throw new BadGatewayException(
      "Faltan credenciales de NewBytes: cargá user + password (portal) o el token de lista de precios"
    );
  }

  /**
   * Catálogo autenticado: GET /v1/ (mismo request que el sitio y el plugin
   * WooCommerce) + descripciones largas de /autoGeneratedDescriptions.
   */
  private async syncFromApi(
    user: string,
    password: string,
    onPage: (items: NormalizedProduct[]) => Promise<void>
  ): Promise<void> {
    const client = await NewBytesApiClient.login(user, password);
    const catalog = unwrapNbList<NbJsonProduct>(await client.get("/"));
    if (catalog.length === 0) throw new BadGatewayException("NewBytes devolvió un catálogo vacío");

    let descriptions = new Map<string, string>();
    try {
      descriptions = descriptionMap(unwrapNbList<NbDescriptionItem>(await client.get("autoGeneratedDescriptions")));
    } catch {
      // La ficha larga es extra: si falla no se pierde el catálogo.
    }

    const BATCH = 200;
    const mapped: NormalizedProduct[] = [];
    for (const row of catalog) {
      const product = mapJsonProduct(row);
      if (!product) continue;
      mapped.push(applyDescription(product, descriptions.get(product.externalId)));
    }
    if (mapped.length === 0) throw new BadGatewayException("NewBytes devolvió un catálogo vacío");
    for (let i = 0; i < mapped.length; i += BATCH) {
      await onPage(mapped.slice(i, i + BATCH));
    }
  }

  /** Lista de precios CSV (token de Integraciones y API). Fallback si no hay user/password. */
  private async syncFromCsv(
    token: string,
    onPage: (items: NormalizedProduct[]) => Promise<void>
  ): Promise<void> {
    const { data } = await axios.get<string>(`${NB_API_BASE}/priceListCsv/${token}`, {
      timeout: 60_000,
      responseType: "text",
    });

    if (typeof data !== "string" || data.trim().startsWith('"El Token')) {
      throw new BadGatewayException("Token de NewBytes inválido o expirado");
    }

    const rows: NbCsvRow[] = parse(data, {
      columns: true,
      delimiter: ";",
      bom: true,
      skip_empty_lines: true,
      relax_column_count: true,
    });

    const BATCH = 200;
    for (let i = 0; i < rows.length; i += BATCH) {
      await onPage(rows.slice(i, i + BATCH).map((r) => mapCsvProduct(r)));
    }
  }

  /**
   * Corrección de ficha producto por producto: descripciones largas (bulk) +
   * GET /item/:id (la ficha que usa el sitio). Corre en background después
   * del sync, igual que Invid. Si un producto puntual falla, se saltea.
   */
  async enrichDetails(
    credentials: Record<string, string>,
    codes: string[],
    onItem: (externalId: string, patch: Partial<NormalizedProduct>) => Promise<void>
  ): Promise<void> {
    const creds = parseNbCredentials(credentials);
    if (!hasNbPortalLogin(creds)) return;

    let client: NewBytesApiClient;
    try {
      client = await NewBytesApiClient.login(creds.user!, creds.password!);
    } catch {
      return;
    }

    let descriptions = new Map<string, string>();
    try {
      descriptions = descriptionMap(unwrapNbList<NbDescriptionItem>(await client.get("autoGeneratedDescriptions")));
    } catch {
      descriptions = new Map();
    }

    for (const code of codes) {
      const patch: Partial<NormalizedProduct> = {};
      const desc = descriptions.get(code);
      if (desc) {
        patch.longDescription = desc;
        patch.description = desc.slice(0, 1000);
      }

      try {
        const item = await client.get(`item/${encodeURIComponent(code)}`);
        Object.assign(patch, extractItemPatch(item));
        if (desc) {
          patch.longDescription = patch.longDescription || desc;
          patch.description = patch.description || desc.slice(0, 1000);
        }
      } catch {
        // ficha puntual no disponible
      }

      if (Object.keys(patch).length > 0) {
        await onItem(code, patch);
      }
      await sleep(120);
    }
  }
}
