-- AlterTable
ALTER TABLE "RetailStore" ADD COLUMN IF NOT EXISTS "priceDivisor" INTEGER NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "RetailIngestRun" ADD COLUMN IF NOT EXISTS "mode" TEXT NOT NULL DEFAULT 'full';
ALTER TABLE "RetailIngestRun" ADD COLUMN IF NOT EXISTS "currentStoreName" TEXT;
ALTER TABLE "RetailIngestRun" ADD COLUMN IF NOT EXISTS "heartbeatAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
